config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  resources :billboards
  resources :songs
  resources :artists
  get "/search", to: "searches#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_and_belongs_to_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_and_belongs_to_many :billboards

#  rails_admin do
#    configure :artist do
#      label 'Owner of the Song: '
#    end
#  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:admin, :artist, :standard]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_view_count_cookie
  private
  def set_view_count_cookie
    if cookies[:views]
      cookies[:views] = cookies[:views].to_i + 1
    else
      cookies[:views] = 0
    end
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all.order(id: :asc)
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to(artists_path) 
    else
      # if nothing was defined here, the render would reuse create
      # When using render the params is preserved. When using redirect the forms values are reset for a new session. Also whenever we change action methods
      render(:new)
    end
  end

  def new
    if current_user && current_user.standard?
      render(plain: "You must be an artist to create new artists.", status: 403)
    end
    @artist = Artist.new 
  end

  def edit
    #authorize
    if current_user && current_user.standard?
      render(plain: "You must be an artist to edit artists.", status: 403)
   end
    @artist = Artist.find(params[:id])  
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to(artists_path)
    else
      render(:edit)
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to(artists_path)
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
  
  def authorize
    if current_user && current_user.standard?
      render(plain: "You must be an artist to edit or create new artists.", status: 403)
    end
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  def index
    @billboards = Billboard.all.order(id: :asc)
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to(billboards_path) 
    else
      # if nothing was defined here, the render would reuse create
      # When using render the params is preserved. When using redirect the forms values are reset for a new session. Also whenever we change action methods
      render(:new)
    end
  end

  def new
    @billboard = Billboard.new 
  end

  def edit
    @billboard = Billboard.find(params[:id])  
  end

  def update
    @billboard = Billboard.find(params[:id])
    if @billboard.update(billboard_params)
      redirect_to(billboards_path)
    else
      render(:edit)
    end
  end

  def destroy
    @billboard = Billboard.find(params[:id])
    @billboard.destroy
    redirect_to(billboards_path)
  end

  private

  def billboard_params
    params.require(:billboard).permit(:title, :country)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
     @billboards = Billboard.order(created_at: :desc).limit(10)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all.order(id: :asc)
    @artists = Artist.all
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to(songs_path) 
    else
      # if nothing was defined here, the render would reuse create
      # When using render the params is preserved. When using redirect the forms values are reset for a new session. Also whenever we change action methods
      render(:new)
    end
  end

  def new
    @song = Song.new
    @artists = Artist.all 
  end

  def edit
    @song = Song.find(params[:id])  
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to(songs_path)
    else
      render(:edit)
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to(songs_path)
  end

  private

  def song_params
    params.require(:song).permit(:title, :released_on, :genre, :rating, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_artist_form.html.erb
<p>
 <%= form_thing.label(:name) %>
 <br/>
 <%= form_thing.text_area(:name) %>
 <br/>
</p>

app/views/artists/_artists.html.erb
<% artists.each do |artist| %>
  <div class="artist-card">
    <p><%= artist.body %></p>
    <date><%= artist.created_at.to_s(:short) %></date>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1> Edit Artist # <%= @artist.id %></h1>
<%= form_for(@artist) do |f| %>
    <%= render("artist_form", form_thing: f) %>
  <%= f.submit("Update") %>

<% end %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<table>
  <thead>
    <tr>
      <td>ID</td>
      <td>Name</td>
    </tr>
  </thead>
  <tbody>
    
<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.id %></td><td><%= artist.name %></td>
    <td><%= link_to("Edit", edit_artist_path(artist.id)) %></td>
    <td><%= link_to("Delete", artist_path(artist.id), method: :delete, data: {confirm: "Are you sure you want to delete #{artist.id}?"}) %></td>
  </tr>
<% end %>

<table>

app/views/artists/new.html.erb
<%= form_for(@artist) do |f| %>

  <%= render("artist_form", form_thing:f) =%>
  <%= f.submit("Save") %>

<% end %>

app/views/billboards/_billboard_form.html.erb
<p>
 <%= form_thing.label(:title) %>
 <br/>
 <%= form_thing.text_area(:title) %>
 <br/>
 <%= form_thing.label(:country) %>
 <br/>
 <%= form_thing.text_field(:country) %>
</p>

app/views/billboards/_billboards.html.erb
<% billboards.each do |billboard| %>
  <tr>
  <td><%= billboard.title %></td><td><%= billboard.country %></td>
  </tr>

<% end %>

app/views/billboards/edit.html.erb
<h1>Edit Billboard #<%= @billboard.id %></h1>

<%= form_for(@billboard) do |f| %>
    <%= render("billboard_form", form_thing: f) %>
  <%= f.submit("Update") %>

<% end %>

app/views/billboards/index.html.erb
<h1>All BillBoards</h1>

<table>
  <thead>
    <tr>
      <td>ID</td>
      <td>Title</td>
      <td>Country</td>
    </tr>
  </thead>
  <tbody>
    
<% @billboards.each do |billboard| %>
  <tr>
    <td><%= billboard.id %></td><td><%= billboard.title %></td><td><%= billboard.country %></td>
    <td><%= link_to("Edit", edit_billboard_path(billboard.id)) %></td>
    <td><%= link_to("Delete", billboard_path(billboard.id), method: :delete, data: {confirm: "Are you sure you want to delete #{billboard.id}?"}) %></td>
  </tr>
<% end %>

<table>

app/views/billboards/new.html.erb
<%= form_for(@billboard) do |f| %>

  <%= render("billboard_form", form_thing:f) =%>
  <%= f.submit("Save") %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <nav>
        <%= link_to("Home", root_path) %>
        <%= link_to("Add New Song", new_song_path) %>
        <%= link_to("Add New Artist", new_artist_path) %>
        <%= link_to("Add New Billboard", new_billboard_path) %>
        <%= link_to("Show Songs", songs_path) %>
        <%= link_to("Show Artists", artists_path) %>
        <%= link_to("Show Billboards", billboards_path) %>
    </nav>
    <%  if current_user %>
             <%= "Hello, #{current_user.email}" %>
         <% end %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Homepage</h1>

<h3>Top 10 Billboards</h3>
<table>
  <thead>
    <tr> 
      <td>Title</td>
      <td>Country</td>
    </tr>
  </thead>
  <tbody>
    <%= render("billboards/billboards", billboards: @billboards) %>
  </tbody>
</table>

app/views/songs/_song_form.html.erb
<p>
 <%= form_thing.label(:title) %>
 <br/>
 <%= form_thing.text_area(:title) %>
 <br/>
 <%= form_thing.label(:released_on) %>
 <br/>
 <%= form_thing.text_field(:released_on) %>
  <br/>
  <%= form_thing.label(:genre) %>
  <br/>
    <%= form_thing.text_field(:genre) %> 
    <br/>
  <%= form_thing.label(:rating) %>
  <br/>
  <%= form_thing.text_field(:rating) %>
  <br/>
 <%= form_thing.label("Artist") %>
 <%= form_thing.select :artist_id, options_for_select(Artist.all.collect { |a| [ a.name, a.id ] }, @song.artist_id) %>
</p>

app/views/songs/_songs.html.erb
<% songs.each do |song| %>
  <div class="song-card">
    <p><%= song.body %></p>
    <date><%= song.created_at.to_s(:short) %></date>
  </div>
<% end %>

app/views/songs/edit.html.erb
<%= form_for(@song) do |f| %>
    <%= render("song_form", form_thing: f) %>
  <%= f.submit("Update") %>

<% end %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<table>
  <thead>
    <tr>
      <td>ID</td>
      <td>Title</td>
      <td>Artist</td>
      <td>Release Date</td>
      <td>Genre</td>
      <td>Rating</td>
    </tr>
  </thead>
  <tbody>
    
<% @songs.each do |song| %>
  <tr>
    <td><%= song.id %></td>
    <td><%= song.title %></td>
    <td><%= "Artist" %></td>
    <td><%= song.released_on %></td>
    <td><%= song.genre %></td>
    <td><%= song.rating %></td>
    <td><%= link_to("Edit", edit_song_path(song.id)) %></td>
    <td><%= link_to("Delete", song_path(song.id), method: :delete, data: {confirm: "Are you sure you want to delete #{song.id}?"}) %></td>
  </tr>
<% end %>
  </tbody>
<table>

app/views/songs/new.html.erb
<%= form_for(@song) do |f| %>

  <%= render("song_form", form_thing:f) =%>
  <%= f.submit("Save") %>

<% end %>

app/views/users/_user.html.erb
i<%= form_for(:user, :url => session_path(:user)) do |form_thing|  %>
<%= form_thing.text_field :email %>

<% end %>